version: '3.8'

services:
  app:
    build: .
    container_name: employee-app
    image: sneha0206/employee-app:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
    restart: always