apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-cicd-app  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emp-cicd-app
  template:
    metadata:
      labels:
        app: emp-cicd-app
    spec:
      containers:
        - name: emp-cicd-app
          image: sneha0206/employee-app:latest
          imagePullPolicy:  Always
          ports:
            - containerPort: 5000

            